services:
    RevisionTen\CQRS\Services\AggregateFactory:
        public: true
        autowire: true
        arguments:
            $container: '@service_container'
    RevisionTen\CQRS\Services\CommandBus:
        public: true
        autowire: true
        arguments:
            $container: '@service_container'
    RevisionTen\CQRS\Services\EventBus:
        public: true
        autowire: true
    RevisionTen\CQRS\Services\EventStore:
        public: true
        autowire: true
    RevisionTen\CQRS\Services\MessageBus:
        public: true
        autowire: true
        arguments:
            $env: '%kernel.environment%'
        tags:
            - { name: monolog.logger, channel: cqrs }
    RevisionTen\CQRS\Services\SnapshotStore:
        public: true
        autowire: true
    RevisionTen\CQRS\Maker\CommandMaker:
        public: true
        autowire: true
        tags: [maker.command]

    # Legacy.
    messagebus: # Todo: Remove this alias once the forms bundle is cleaned up.
        alias: RevisionTen\CQRS\Services\MessageBus
        public: true

doctrine:
    orm:
        mappings:
            CQRSBundle:
                mapping: true
                type: annotation
                dir: 'Model'
                alias: CQRSBundle
                prefix: 'RevisionTen\CQRS\Model'
                is_bundle: true
